#!/usr/bin/env python3
"""Export skill wrappers for multiple coding-agent CLIs."""

from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / "qa-skills-plugin" / "skills"
INTEGRATIONS_ROOT = REPO_ROOT / "integrations"


def parse_frontmatter(skill_file: Path) -> tuple[str, str]:
    text = skill_file.read_text(encoding="utf-8")
    _, raw, _rest = text.split("---\n", 2)
    data: dict[str, str] = {}
    for line in raw.splitlines():
        if not line.strip():
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip()
    return data["name"], data["description"]


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def write(path: Path, content: str) -> None:
    ensure_parent(path)
    path.write_text(content, encoding="utf-8")


def claude_prompt(name: str) -> str:
    return f"""---
description: Run the `{name}` QA workflow against the current task
argument-hint: [optional scope or task details]
---

Use the skill definition at @qa-skills-plugin/skills/{name}/SKILL.md.

Follow its deterministic execution flow exactly.
Load only the references you need from @qa-skills-plugin/skills/{name}/references/.
Treat `examples/`, `scripts/`, `test/`, and `assets/` as optional helpers when they exist.

Apply the skill to this request: $ARGUMENTS
If `$ARGUMENTS` is empty, infer the target from the current conversation and repository context.
"""


def gemini_prompt(name: str, description: str) -> str:
    return f'''description = "{description}"

prompt = """Use the skill definition at `qa-skills-plugin/skills/{name}/SKILL.md`.

Follow its deterministic execution flow exactly.
Load only the references you need from `qa-skills-plugin/skills/{name}/references/`.
Treat `examples/`, `scripts/`, `test/`, and `assets/` as optional helpers when they exist.

Apply the skill to this request: {{{{args}}}}
If `{{{{args}}}}` is empty, infer the target from the current conversation and repository context.
"""
'''


def opencode_prompt(name: str) -> str:
    return f"""---
description: Run the `{name}` QA workflow against the current task
---

Read `qa-skills-plugin/skills/{name}/SKILL.md` from the current repository.

Follow its deterministic execution flow exactly.
Load only the references you need from `qa-skills-plugin/skills/{name}/references/`.
Treat `examples/`, `scripts/`, `test/`, and `assets/` as optional helpers when they exist.

Apply the skill to this request: $ARGUMENTS
If `$ARGUMENTS` is empty, infer the target from the current conversation and repository context.
"""


def main() -> int:
    skill_dirs = sorted(path for path in SKILLS_ROOT.iterdir() if path.is_dir())
    for skill_dir in skill_dirs:
        name, description = parse_frontmatter(skill_dir / "SKILL.md")
        write(INTEGRATIONS_ROOT / "claude" / ".claude" / "commands" / "qa" / f"{name}.md", claude_prompt(name))
        write(INTEGRATIONS_ROOT / "gemini" / ".gemini" / "commands" / "qa" / f"{name}.toml", gemini_prompt(name, description))
        write(INTEGRATIONS_ROOT / "opencode" / ".opencode" / "commands" / "qa" / f"{name}.md", opencode_prompt(name))

    write(
        INTEGRATIONS_ROOT / "README.md",
        """# Generated command wrappers

This directory is generated by `scripts/export_agent_commands.py`.

- `claude/.claude/commands/qa/`: Claude Code custom slash commands
- `gemini/.gemini/commands/qa/`: Gemini CLI custom commands
- `opencode/.opencode/commands/qa/`: OpenCode custom commands
""",
    )
    print(f"Exported wrappers for {len(skill_dirs)} skills.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
